sudo: false
language: python
python:
  - "2.7"
install:
  - case "$TRAVIS_PYTHON_VERSION" in
    2*)
      wget http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh;
      PYTHON="python"
      ;;
    3*)
      wget http://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
      PYTHON="python3"
      ;;
    esac
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  - conda info -a
  - conda config --add channels conda-forge
  - conda create -q -n env
  - source activate env
  - conda install --file requirements/conda.txt
  - pip install -e .
  - pip install -r requirements/development.txt
script:
  - source activate env
  - export FLASK_APP=dicom_flask_uploader.runapp
  - flask initdb
  - py.test --cov
after_success:
  - bash <(curl -s https://codecov.io/bash)
